var qbData = [
{'quarterback': 'Tom Brady', 'team': 'NEP', 'home_away': '@', 'opponent': 'OAK', 'adjPF': '22', 'adjPA': '21.2', 'Proj': '22.6'},
{'quarterback': 'Alex Smith', 'team': 'KCC', 'home_away': '@', 'opponent': 'NYG', 'adjPF': '22', 'adjPA': '21.1', 'Proj': '21.4'},
{'quarterback': 'Carson Wentz', 'team': 'PHI', 'home_away': '@', 'opponent': 'DAL', 'adjPF': '21.9', 'adjPA': '19.1', 'Proj': '21'},
{'quarterback': 'Russell Wilson', 'team': 'SEA', 'home_away': 'vs.', 'opponent': 'ATL', 'adjPF': '21.5', 'adjPA': '17.1', 'Proj': '20.4'},
{'quarterback': 'Drew Brees', 'team': 'NOS', 'home_away': 'vs.', 'opponent': 'WAS', 'adjPF': '19.3', 'adjPA': '17.3', 'Proj': '19.7'},
{'quarterback': 'Dak Prescott', 'team': 'DAL', 'home_away': 'vs.', 'opponent': 'PHI', 'adjPF': '20.9', 'adjPA': '18.1', 'Proj': '19.5'},
{'quarterback': 'Ben Roethlisberger', 'team': 'PIT', 'home_away': 'vs.', 'opponent': 'TEN', 'adjPF': '16.3', 'adjPA': '20.6', 'Proj': '18.4'},
{'quarterback': 'Derek Carr', 'team': 'OAK', 'home_away': 'vs.', 'opponent': 'NEP', 'adjPF': '17.6', 'adjPA': '21.1', 'Proj': '18.4'},
{'quarterback': 'Ryan Fitzpatrick', 'team': 'TBB', 'home_away': '@', 'opponent': 'MIA', 'adjPF': '20.3', 'adjPA': '21.2', 'Proj': '18.3'},
{'quarterback': 'Kirk Cousins', 'team': 'WAS', 'home_away': '@', 'opponent': 'NOS', 'adjPF': '20.8', 'adjPA': '15.8', 'Proj': '17.9'},
{'quarterback': 'Blake Bortles', 'team': 'JAC', 'home_away': '@', 'opponent': 'CLE', 'adjPF': '16.6', 'adjPA': '22.7', 'Proj': '17.8'},
{'quarterback': 'Matthew Stafford', 'team': 'DET', 'home_away': '@', 'opponent': 'CHI', 'adjPF': '20.3', 'adjPA': '14.4', 'Proj': '17.4'},
{'quarterback': 'Jay Cutler', 'team': 'MIA', 'home_away': 'vs.', 'opponent': 'TBB', 'adjPF': '14.6', 'adjPA': '20.7', 'Proj': '17.2'},
{'quarterback': 'Tyrod Taylor', 'team': 'BUF', 'home_away': '@', 'opponent': 'LAC', 'adjPF': '17.1', 'adjPA': '15.2', 'Proj': '16.8'},
{'quarterback': 'Blaine Gabbert', 'team': 'ARI', 'home_away': '@', 'opponent': 'HOU', 'adjPF': '11.6', 'adjPA': '22.2', 'Proj': '16.6'},
{'quarterback': 'Philip Rivers', 'team': 'LAC', 'home_away': 'vs.', 'opponent': 'BUF', 'adjPF': '15.7', 'adjPA': '14.7', 'Proj': '16.5'},
{'quarterback': 'Case Keenum', 'team': 'MIN', 'home_away': 'vs.', 'opponent': 'LAR', 'adjPF': '15.7', 'adjPA': '13.8', 'Proj': '16.2'},
{'quarterback': 'Jared Goff', 'team': 'LAR', 'home_away': '@', 'opponent': 'MIN', 'adjPF': '17.9', 'adjPA': '15.8', 'Proj': '16.2'},
{'quarterback': 'Andy Dalton', 'team': 'CIN', 'home_away': '@', 'opponent': 'DEN', 'adjPF': '16.2', 'adjPA': '17', 'Proj': '16'},
{'quarterback': 'Eli Manning', 'team': 'NYG', 'home_away': 'vs.', 'opponent': 'KCC', 'adjPF': '17', 'adjPA': '18.7', 'Proj': '15.7'},
{'quarterback': 'Marcus Mariota', 'team': 'TEN', 'home_away': '@', 'opponent': 'PIT', 'adjPF': '17.3', 'adjPA': '13.8', 'Proj': '15.6'},
{'quarterback': 'Matt Ryan', 'team': 'ATL', 'home_away': '@', 'opponent': 'SEA', 'adjPF': '16.9', 'adjPA': '14.9', 'Proj': '15.6'},
{'quarterback': 'Brock Osweiler', 'team': 'DEN', 'home_away': 'vs.', 'opponent': 'CIN', 'adjPF': '11.4', 'adjPA': '17.4', 'Proj': '14.2'},
{'quarterback': 'Tom Savage', 'team': 'HOU', 'home_away': 'vs.', 'opponent': 'ARI', 'adjPF': '9.7', 'adjPA': '19', 'Proj': '14.2'},
{'quarterback': 'Mitchell Trubisky', 'team': 'CHI', 'home_away': 'vs.', 'opponent': 'DET', 'adjPF': '9.8', 'adjPA': '17.1', 'Proj': '13.7'},
{'quarterback': 'Joe Flacco', 'team': 'BAL', 'home_away': '@', 'opponent': 'GBP', 'adjPF': '8.5', 'adjPA': '18.4', 'Proj': '13.2'},
{'quarterback': 'DeShone Kizer', 'team': 'CLE', 'home_away': 'vs.', 'opponent': 'JAC', 'adjPF': '13.9', 'adjPA': '9.9', 'Proj': '12.4'},
{'quarterback': 'Brett Hundley', 'team': 'GBP', 'home_away': 'vs.', 'opponent': 'BAL', 'adjPF': '11.2', 'adjPA': '14', 'Proj': '12.3'}
];

var matchups = [
'Tom Brady (NEP @ OAK): 22.6 proj. pts.', 
'Alex Smith (KCC @ NYG): 21.4 proj. pts.', 
'Carson Wentz (PHI @ DAL): 21 proj. pts.', 
'Russell Wilson (SEA vs. ATL): 20.4 proj. pts.', 
'Drew Brees (NOS vs. WAS): 19.7 proj. pts.', 
'Dak Prescott (DAL vs. PHI): 19.5 proj. pts.', 
'Ben Roethlisberger (PIT vs. TEN): 18.4 proj. pts.', 
'Derek Carr (OAK vs. NEP): 18.4 proj. pts.', 
'Ryan Fitzpatrick (TBB @ MIA): 18.3 proj. pts.', 
'Kirk Cousins (WAS @ NOS): 17.9 proj. pts.', 
'Blake Bortles (JAC @ CLE): 17.8 proj. pts.', 
'Matthew Stafford (DET @ CHI): 17.4 proj. pts.', 
'Jay Cutler (MIA vs. TBB): 17.2 proj. pts.', 
'Tyrod Taylor (BUF @ LAC): 16.8 proj. pts.', 
'Blaine Gabbert (ARI @ HOU): 16.6 proj. pts.', 
'Philip Rivers (LAC vs. BUF): 16.5 proj. pts.', 
'Case Keenum (MIN vs. LAR): 16.2 proj. pts.', 
'Jared Goff (LAR @ MIN): 16.2 proj. pts.', 
'Andy Dalton (CIN @ DEN): 16 proj. pts.', 
'Eli Manning (NYG vs. KCC): 15.7 proj. pts.', 
'Marcus Mariota (TEN @ PIT): 15.6 proj. pts.', 
'Matt Ryan (ATL @ SEA): 15.6 proj. pts.', 
'Brock Osweiler (DEN vs. CIN): 14.2 proj. pts.', 
'Tom Savage (HOU vs. ARI): 14.2 proj. pts.', 
'Mitchell Trubisky (CHI vs. DET): 13.7 proj. pts.', 
'Joe Flacco (BAL @ GBP): 13.2 proj. pts.', 
'DeShone Kizer (CLE vs. JAC): 12.4 proj. pts.', 
'Brett Hundley (GBP vs. BAL): 12.3 proj. pts.', 
]